### ISSUE TITLE
Keep having to restart standalone_hostonly_snat.service

### ISSUE THREAD

**Issue by adduarte** [shiftstack/dev-install#28] opened 2021-03-30 01:37 UTC
For some reason, in several deployments, even though the standalone_hostonly_snat.service status shows that it was run and it added the required iptables rule to the nat table  (iptables --list -t nat), the rule is not there. 
The solution is easy, just "sudo systemctl restart standalone_host_only_snat.service" reads the rule, 

Probably something else is clearing the iptables.

**Comment by EmilienM** [comment] 2021-06-10 16:22
I couldn't reproduce it, i'm closing it but please re-open if you saw it recently.

**Closed by EmilienM** 2021-06-10 16:22 UTC
